# -*- coding: utf-8 -*-
"""Idade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17dznTo1ObyjlrjfZLPH2t8gdfXeLRAz3

#Code Park

Desenvolva um programa que recebe do usuário nome completo e ano de nascimento que seja entre 1922 e 2021.
A partir dessas informações, o sistema mostrará o nome do usuário e a idade que completou, ou completará, no ano atual (2022).

Caso o usuário não digite um número ou apareça um inválido no campo do ano, o sistema informará o erro e continuará perguntando até que um valor correto seja preenchido.
"""

while True:
    nome_completo = input("Digite seu nome completo: ")
    ano_nascimento = input("Digite seu ano de nascimento (entre 1922 e 2021): ")
    try:
        ano_nascimento = int(ano_nascimento)
        if ano_nascimento < 1922 or ano_nascimento > 2021:
            raise ValueError
        break
    except ValueError:
        print("Ano de nascimento inválido. Tente novamente.")


idade = 2022 - ano_nascimento

print("Seu nome completo é: ", nome_completo)
print("Você tem ",idade, "anos.")